version: "2"
services:
  app:
    build: ./app
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app:rw
      
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./data/mysql:/var/lib/mysql
