apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: mysql-claim0
          readOnly: true
        - mountPath: /var/lib/mysql
          name: mysql-claim1
      volumes:
        - name: mysql-claim1
          persistentVolumeClaim:
            claimName: mysql-claim1    
        - name: mysql-claim0
          configMap:
            name: mysql-initdb-config   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE knights;
    use knights;
    
    CREATE TABLE channels (
      id MEDIUMINT NOT NULL AUTO_INCREMENT,
      title VARCHAR(128) NOT NULL,
      link VARCHAR(256) NOT NULL,
      description VARCHAR(1024),
      PRIMARY KEY (id)
    );
    
    
    INSERT INTO channels
      (title, link, description)
    VALUES
      ('Lancelot', 'Lancelot', 'blue'),
      ('Galahad', 'Lancelot', 'yellow');
    
    CREATE TABLE channel_entries (
      id MEDIUMINT NOT NULL AUTO_INCREMENT,
      channel_id INT NOT NULL,
      title VARCHAR(128) NOT NULL,
      link VARCHAR(256) NOT NULL,
      description VARCHAR(1024) NOT NULL,
      PRIMARY KEY (id)
    );
    
    INSERT INTO channel_entries
      (channel_id, title, link, description)
    VALUES
      (1, 'Galahsad', 'Lancqelot', 'yelloww'),
      (2, 'Galadhad', 'Lanceloqt', 'yelleow');
    
    CREATE TABLE channel_entries_datetimes (
      id MEDIUMINT NOT NULL,
      datetime INT,
      PRIMARY KEY (id)
    );